# Generated by Django 4.0.5 on 2022-06-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
