# Generated by Django 4.0.5 on 2022-06-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmessage',
            name='encode_tasks_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='encode_tasks_total',
            field=models.IntegerField(default=0),
        ),
    ]
